apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: loki
    app.kubernetes.io/version: 1.6.1
  name: loki
  namespace: loki
spec:
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: loki
  sessionAffinity: ClientIP
  type: ClusterIP
