apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lokiclusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lokiclusterrole
subjects:
- kind: ServiceAccount
  name: loki-promtail
  namespace: loki
